### ISSUE TITLE
Does not support some languages

### ISSUE THREAD

**Issue by carlosepp** [grosser/i18n_data#18]
<img width="269" alt="screen shot 2015-09-17 at 1 31 40 pm" src="https://cloud.githubusercontent.com/assets/497142/9942410/767ceade-5d40-11e5-8c41-1d9651b1481c.png">

My code is crashing because it returns nil, wouldn't it be better to throw an empty string to prevent crashes?

**Comment by carlosepp** [comment]
Detected that also Mandarin, Quechua, Hindi, Korean, Danish, Urdu, Tamil, Yorkshire, Swahili

**Comment by grosser** [comment]
nah nil is what I'd expect ... you can do .to_s if you don't like nils :)
