### ISSUE TITLE
Ruby 1.9.2 support?

### ISSUE THREAD

**Issue by luckydev** [grosser/i18n_data#28]
Is there any reason why we require Ruby >= 1.9.3 

If there is no specific reason, can you please switch the ruby dependency to Ruby >= 1.9.2 ?

One of my apps is using Ruby 1.9.2 and its depending on `countries` gem v1.2.5. Which in turn wants i18n_data gem v0.7.0

**Comment by grosser** [comment]
- should not use a ruby version that does not get security updates anymore
 - upgrading to 1.9.3 should be trivial
 - can make a fork, remove the requirement and then use that via git

**Comment by luckydev** [comment]
Thanks for the response.
