### ISSUE TITLE
counties-ZH_CN.txt line 32   波利维亚   玻利维亚

### ISSUE THREAD

**Issue by misty44** [grosser/i18n_data#43]
玻利维亚 is Correct translation

**Comment by misty44** [comment]
柬埔塞  -> 柬埔寨

**Comment by grosser** [comment]
translations are from http://git.debian.org/?p=iso-codes/iso-codes.git so improvement suggestions should go there
since that repo has moved again I'll look into updating and maybe that fixes things ...

**Comment by grosser** [comment]
just updated and nothing changed, so take this to pkg-isocodes 🤷‍♂️
