### ISSUE TITLE
Incorrect translation of "North Macedonia" to Serbian

### ISSUE THREAD

**Issue by pmor** [grosser/i18n_data#53]
Reported to https://github.com/countries/countries/issues/703, but the data comes from this gem.

In Serbian (SR) and Macedonian (MK) cache files, "North Macedonia" is translated to "Нова Каледонија" which is "New Caledonia"

The correct translation should be "Северна Македонија", as per https://salsa.debian.org/iso-codes-team/iso-codes/-/blob/main/iso_3166-1/sr.po

**Comment by grosser** [comment]
can you try running an update and see if that fixes the issue?
https://github.com/grosser/i18n_data#development

**Comment by pmor** [comment]
Yeah, I'm setting it up locally to see if I can push a PR for this

**Comment by pmor** [comment]
I'm pushing a PR in a few minutes that fixes the Serbian data, but not the Macedonian data. 

It's also not a full update of the data, because I think there might be some issue going on.

I don't actually read Serbian, but using google translate, the update seems to be trying to rename `KR` (South Korea) to  `Јужна Африка` which translates to `South Africa` (in `cache/file_data_provider/countries-SR.txt`)

And in `cache/file_data_provider/countries-MK.txt`), the translation for `MK` is still incorrect, and it's trying to rename North Korea (KP) to New Caledonia (`Нова Каледонија`)
