### ISSUE TITLE
Incorrect Translations

### ISSUE THREAD

**Issue by pmor** [grosser/i18n_data#57]
The data update in #56 applied incorrect translations to a number of country files, such as:

https://github.com/grosser/i18n_data/blob/f76b23dd512ec0071200020a408eecd2df190a5c/cache/file_data_provider/countries-AN.txt#L182

and 

https://github.com/grosser/i18n_data/blob/f76b23dd512ec0071200020a408eecd2df190a5c/cache/file_data_provider/countries-AN.txt#L122

Where KP is being translated to "New Caledonia" and KR to "South Africa". In some cases also KR as "North Macedonia"

It seems to be the potencial issue I mentioned in https://github.com/grosser/i18n_data/issues/53#issuecomment-981988464

In a quick review this affected country files for: AF, AN, possibly AK, AZ, BR, BS, CA, CS, CY, DA, EU, FI, FO, FY, GA, GL, GN, GV, HA, HT, HU, IA, IO, IT, KI, KW, LT, LV, MS, MT, NA, NN, PL, PT, RO, RW, SK, SL, SO, SQ, SW, TK, TL, UZ, VE, VI, WA, WO, XH, YO, ZU

I didn't check the country files that use non-latin alphabets

**Comment by grosser** [comment]
#56 was an automated update from upstream and it included #54 and #55 so I was hoping it's correct :(

can you check with https://salsa.debian.org/iso-codes-team/iso-codes what they think about this issue (if they did that on purpose or possibly have a PR to fix it open already)

**Comment by pmor** [comment]
The data for the Portuguese (PT) file would be from this file?  https://salsa.debian.org/iso-codes-team/iso-codes/-/blob/main/iso_3166-1/pt.po

If so, the content appears to have the correct names for both Koreas, so it might be an issue with the task that updates the files? I'll do some debugging to see if I can figure out where those mismatches might be coming from

**Comment by grosser** [comment]
thx!

**Comment by pmor** [comment]
The Salsa files are broken, I didn't notice at first, but this commit messed up a bunch of things: https://salsa.debian.org/iso-codes-team/iso-codes/-/commit/7be63e83d865c53aa3f5592eba389d4ea30065ce

I didn't have a profile there, so I'm waiting for approval before I report this

**Comment by grosser** [comment]
thx, good digging :D

**Comment by pmor** [comment]
FYI, reported upstream https://salsa.debian.org/iso-codes-team/iso-codes/-/issues/35

**Comment by pmor** [comment]
From Salsa, the issue is the incorrect data is auto-generated translations that are marked as "fuzzy" in the `po` files, but the parsing in `LiveDataProvider` doesn't take that into account.

I can look into refactoring `LiveDataProvider`  to use arashm/PoParser, to get the `po` files fully parsed so the fuzzy translations can be ignored.
