### ISSUE TITLE
Capitalization of languages in Norwegian and Swedish

### ISSUE THREAD

**Issue by robbertbrak** [grosser/i18n_data#65]
The capitalization of languages in Norwegian seems inconsistent. For example: [NO;;Norsk](https://github.com/grosser/i18n_data/blob/master/cache/file_data_provider/languages-NB.txt#L120) is capitalized, but [NE;;nepalsk](https://github.com/grosser/i18n_data/blob/master/cache/file_data_provider/languages-NB.txt#L116) is not. According to e.g. https://help.unbabel.com/hc/en-us/articles/360034571294-Language-Guidelines-Norwegian#33capitalization, language names should *NOT* be capitalized in Norwegian.

For Swedish, it looks like all the language names are currently capitalized (https://github.com/grosser/i18n_data/blob/master/cache/file_data_provider/languages-SV.txt). However, according to e.g. https://blogs.transparent.com/swedish/use-of-capital-letters/, this is not correct.

Would you consider adjusting the use of capitalization for Norwegian and Swedish?

**Comment by grosser** [comment]
changes should go into iso codes package see https://github.com/grosser/i18n_data?tab=readme-ov-file#translations
refresh might already fix it ... but otherwise make an issue there

**Comment by robbertbrak** [comment]
@grosser: thank you for pointing me in the right direction. I'll raise an issue with them about the inconsistent capitalization of Norwegian.

For Swedish, they take the stance that they capitalized the language names because they are presented [as a list](https://salsa.debian.org/iso-codes-team/iso-codes/-/blob/main/iso_639-2/sv.po?ref_type=heads#L23), which makes sense to me.

I also noticed that [French](https://salsa.debian.org/iso-codes-team/iso-codes/-/blob/main/iso_639-2/fr.po) was recently (5 months ago) updated so that they now also present all the language names with initial capitals. Maybe time to refresh i18n_data with the latest data from the iso codes package?

**Comment by grosser** [comment]
yeah, try updating with https://github.com/grosser/i18n_data?tab=readme-ov-file#development
