### ISSUE TITLE
Ability to sort country names using locales

### ISSUE THREAD

**Issue by pjg** [grosser/i18n_data#8]
It would be great if there was a way to sort country names differently based on locales (something in databases is done using `COLLATE` - http://www.postgresql.org/docs/9.4/static/collation.html). This way we can present properly sorted country names to the user.

Just an idea.

**Comment by grosser** [comment]
this could help: https://github.com/grosser/sort_alphabetical

**Comment by pjg** [comment]
Thanks! It's not ideal, but it heaps better :)
